name: Build
on: [ push, pull_request ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        output:
        - kernelPatches.enarx.patch
        - linuxPackages_enarx.kernel
        - rathole
        - sgx-psw
        - rathole
        os:
        - ubuntu-20.04
        - macos-latest
        exclude:
          - output: sgx-psw
            os: macos-latest
          - output: linuxPackages_enarx.kernel
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: enarx
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build ${{ matrix.output }}
      run: nix build -L '.#${{ matrix.output }}'
